#include "cli_usage.hpp"
#include "version.hpp"

#include <iostream>

namespace gffsub {

void usage(const char* prog) {
    std::cerr
        << "Program: gffsub (subset GFF3/GTF annotations)\n"
        << "Version: " << kVersion << "\n"
        << "\n"
        << "Usage:   " << prog << " <input.gff3> [options]\n"
        << "         " << prog << " query|window <input.gff3> [options]\n"
        << "\n"
        << "Selector options:\n"
        << "  --id ID                      exact feature ID (repeatable)\n"
        << "  --ids FILE                   one exact ID per non-empty line\n"
        << "  --name NAME                  gene by ID/Name/gene_id/locus_tag/Alias/Dbxref\n"
        << "  --where KEY=VALUE            exact column-9 attribute (repeatable)\n"
        << "  --grep FIELD:PATTERN         field/attribute contains PATTERN (repeatable)\n"
        << "  --grep-regex FIELD:REGEX     field/attribute matches REGEX (repeatable)\n"
        << "  --grep-file FILE             patterns for --grep-field (one per line)\n"
        << "  --grep-field FIELD           field for --grep-file [required with --grep-file]\n"
        << "  --grep-file-regex            treat --grep-file lines as regex\n"
        << "  -I, --include-expr EXPR      keep records matching expression (repeatable)\n"
        << "  -E, --exclude-expr EXPR      drop records matching expression (repeatable)\n"
        << "  -v, --invert-match           invert grep matches\n"
        << "  --ignore-case                case-insensitive grep/expression strings\n"
        << "  -C, --children               include descendants of selector hits\n"
        << "  --parents                    include ancestors of selector hits\n"
        << "  --model                      include full gene model of selector hits\n"
        << "  --nearest REGION             nearest gene to 1-based CHR:START-END\n"
        << "  --out-attrs KEYS             print selected attributes (summary output)\n"
        << "  --summary FMT                summary instead of GFF3: tsv|json\n"
        << "  --up N, --down N             window around --id (bp) [0]\n"
        << "  --strand-aware               window follows feature strand\n"
        << "\n"
        << "Input/region options:\n"
        << "  --seqid LIST                 keep seqids (comma-separated); ^LIST excludes\n"
        << "  --source SOURCE              exact source column (2nd)\n"
        << "  --score SCORE                score column (6th); use . for missing\n"
        << "  -r, --region REGION          overlap 1-based inclusive CHR:START-END\n"
        << "  -b, --bed FILE               overlap BED intervals (0-based half-open)\n"
        << "\n"
        << "Feature filter options:\n"
        << "  -f, --feature TYPE           type column (3rd), e.g. gene,mRNA,exon,CDS\n"
        << "  --strand STRAND              strand column: +|-|.|?\n"
        << "  --phase PHASE                phase column: 0|1|2|.\n"
        << "  -L, --longest                one transcript/gene: CDS length if any CDS, else exon\n"
        << "  -@, --threads N              threads for --longest [1]\n"
        << "\n"
        << "Output options:\n"
        << "  -t, --format FMT             gff3|gtf|gtf2|gtf3|bed [gff3]\n"
        << "  -o, --output FILE            write to FILE [stdout]\n"
        << "  -h, --help                   show this help\n"
        << "  --version                    print version and exit\n"
        << "\n"
        << "Aliases: --id-list=--ids  --attr=--where  --include-children=-C\n"
        << "         --include-parents=--parents  --gene-model=--model\n"
        << "         --nearest-gene=--nearest  --output-attrs/--attrs=--out-attrs\n"
        << "         --summary-format=--summary  --upstream=--up  --downstream=--down\n"
        << "         --type/--feature=-f  --output-format=--format\n"
        << "\n"
        << "Examples:\n"
        << "  " << prog << " ann.gff3 -r chr1:1-100000 -f gene\n"
        << "  " << prog << " ann.gff3 --id GeneA -C\n";
}

void query_usage(const char* prog) {
    std::cerr
        << "About:   query features by ID, name, region, or attributes\n"
        << "Usage:   " << prog << " query <input.gff3> [options]\n"
        << "\n"
        << "Options:\n"
        << "  --id ID                 exact feature ID\n"
        << "  --ids FILE              one ID per line\n"
        << "  --name NAME             gene naming keys\n"
        << "  --region CHR:START-END  1-based inclusive overlap\n"
        << "  --type TYPE             restrict by feature type\n"
        << "  --where KEY=VALUE       exact attribute\n"
        << "  --out-attrs KEYS        selected attributes in summary\n"
        << "  -C, --children          include descendants\n"
        << "  --parents               include ancestors\n"
        << "  --model                 full gene model\n"
        << "  --nearest REGION        nearest gene (1-based region)\n"
        << "  --summary FMT           tsv|json instead of GFF3\n"
        << "  -h, --help              show this help\n"
        << "\n"
        << "Example:\n"
        << "  " << prog << " query ann.gff3 --id GeneA --summary tsv\n";
}

void window_usage(const char* prog) {
    std::cerr
        << "About:   records overlapping a window around one feature\n"
        << "Usage:   " << prog << " window <input.gff3> --id ID [options]\n"
        << "\n"
        << "Options:\n"
        << "  --id ID                 target feature ID or gene key (required)\n"
        << "  --up N, --upstream N    bases upstream [0]\n"
        << "  --down N, --downstream N  bases downstream [0]\n"
        << "  --strand-aware          window follows feature strand\n"
        << "  -h, --help              show this help\n"
        << "\n"
        << "Example:\n"
        << "  " << prog << " window ann.gff3 --id GeneA --up 2000 --down 500\n";
}

}  // namespace gffsub
